spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:postgresql://localhost:5432/paymentdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

server:
  port: 8084

services:
  order:
    url: http://localhost:8083

payment:
  public-url: http://localhost:8084
